### ISSUE TITLE
customizeRemote

### ISSUE THREAD

**Issue by paulvh** [paulvh/capstone-project#2]

**Comment by paulvh** [comment]
### Value Statement

As a Raspberry Tinkerer
I need to customize my UI
so that I can control different raspberry-projects

### Description

![IMG_0573](https://user-images.githubusercontent.com/721780/86531010-037feb00-bebe-11ea-8854-be823414d8ae.jpg)

### Acceptance Criteria

- [ ] I want to choose how many input-elements my UI has
- [ ] I want to choose the order of my input-elements
- [ ] I want to choose between different input-elements (button, range, text-input)
- [ ] I want to set the IP and Port to my project-server

### Tasks

- [ ] Add edit remote page
- [ ] Add select element page
- [ ] Add new components range and text-input
- [ ] Testing

### Size
Big
