### ISSUE TITLE
customizeRemote

### ISSUE THREAD

**Issue by paulvh** [paulvh/capstone-project#3]
### Value Statement

As a Raspberry Tinkerer
I need to customize my UI
so that I can control different raspberry-projects

### Description
![IMG_0573](https://user-images.githubusercontent.com/721780/86531249-e1876800-bebf-11ea-829e-361fe988e345.jpg)

### Acceptance Criteria

- [ ] I want to choose the quantity and placement of input-elements
- [ ] I want to choose between different input-elements (button, range, text-input)
- [ ] I want to set the IP and Port of my project-server
- [ ] I want to set the messages being sent by the input-elements

### Tasks

- [ ] Add a create-remote page
- [ ] Add a select-element page
- [ ] Add link to navigate to the create-remote page
- [ ] Testing

### Size
Big
